export const products = [
	{
		id: 1,
		title: "H&M shirt",
		brand: "levis",
		price: "999",
		size: "L",
		category: "men",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 2,
		title: "product two",
		brand: "puma",
		price: "1999",
		size: "M",
		category: "women",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 3,
		title: "product 3",
		brand: "nike",
		price: "2999",
		size: "XL",
		category: "women",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 4,
		title: "Product 4",
		brand: "avaasa",
		price: "999",
		size: "L",
		category: "men",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 5,
		title: "product 5",
		brand: "nike",
		price: "1299",
		size: "L",
		category: "men",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 6,
		title: "product 6",
		brand: "puma",
		price: "899",
		size: "S",
		category: "kids",
		img: "https://picsum.photos/200/300",
	},
	{
		id: 7,
		title: "H&M shirt",
		brand: "levis",
		price: "999",
		size: "L",
		category: "men",
		img: "https://picsum.photos/200/300",
	},
];
